# Generated by Django 4.1.1 on 2022-09-12 21:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_alter_comment_article"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="datetime",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
